### PR TITLE
Fleshed out section 2: "introduction to dataflow programming."

### PR DESCRIPTION
**Pull request by col6y**
[The latest revision of the documentation is, of course, up online.](http://cgscomwww.catlin.edu/~skeggsc/ccre-docs/)

### CODE REVIEW

**Comment by amackworth** [comment]
Also, shouldn't this section also mention `[Event/Float/Boolean]Status` as well?

**Comment by col6y** [comment]
You know you can comment on the PR directly, right? You don't have to go to the commits individually.

**Comment by amackworth** [comment]
Oh, whoops! Sorry :sweat:

**Comment by col6y** [comment]
Updated.

**Comment by amackworth** [comment]
Alright, looks good to go! :sparkles:

**Pull request merged**
