### PR TITLE
Add PWM support for unsupported controllers

### PR DESCRIPTION
**Pull request by col6y**
Add support for Talon SRX (over PWM), Spark, SD540, and Jaguar SP.

I really should have remembered this earlier.

### CODE REVIEW

**Comment by amackworth** [comment]
Hmm...this may be outside of the scope of this PR, but the duplication of all the `FRC.[motor type]()` methods bugs me. Seems to me it might be possible to abstract some of that away eventually?

**Comment by amackworth** [comment]
(Otherwise, this looks ready to merge. :+1:)

**Comment by col6y** [comment]
It bugs me too. However, you know how Java works, and it's hard to get around.
It's important for the perceived usability of the project to be able to write something as simple as `FRC.talon(5)` and have it work.

**Comment by amackworth** [comment]
Oh, agreed! I just meant the duplication of the internals.

**Comment by col6y** [comment]
Oh yeah. Feel free to file a bug report.

**Comment by amackworth** [comment]
Will do!

:sparkles: mergin' :sparkles:

**Pull request merged**
