### PR TITLE
Refactor setup mode EventOutputs into CancelOutputs

### PR DESCRIPTION
**Pull request by col6y**
(A bite-sized portion of the mergeable changes.)

The idea here is that I'm trying to (in the documentation) specifically separate "setup mode" from "flow mode", and EventOutputs were being used in a strange in-between place where some EventOutputs are flow mode and some are setup mode. Instead of that, there's now separate interfaces for the two. It's clearer: it's easier to explain why `send` returns a CancelOutput rather than explaining why `send` returns an EventOutput.

This PR is followed by #133.

### CODE REVIEW

**Comment by amackworth** [comment]
So, to be clear, this means that only CancelOutputs should be used in setup mode? (or vice versa?)

**Comment by amackworth** [comment]
(Otherwise, this looks ready to merge.)

**Comment by col6y** [comment]
CancelOutputs are only used in setup mode, yes. And EventOutputs only in flow mode, just like BooleanOutputs and FloatOutputs.

**Comment by amackworth** [comment]
Alright, sounds good.

:sparkles: merging :sparkles:

**Pull request merged**
